### ISSUE TITLE
How to train compression?

### ISSUE THREAD

**Issue by xinchundong** [DerrickXuNu/OpenCOOD#10]
Hi, thanks for the great work for cooperative perception! I have a question regarding to compression. How do you train the intermediate fusion with compression?  And will you also provide all the weights with compression?

**Comment by DerrickXuNu** [comment]
Thanks for your interest in this project! Typically, we first train on the data without compression. After the training is done, we use the trained model and add compression on it (change the compression flag in the yaml file) to fine-tune it. We already provided the compression weights for the models that appear in our paper. For other newly implemented methods (such as F-Cooper and V2VNet), we will just provide the pre-trained model without compression, and you can use those as a start point and choose the compression function/rate you want to fine-tune on the data. It should be very straigtforward.

**Comment by xinchundong** [comment]
Thank you. That makes a lot of sense.
