### ISSUE TITLE
Something about the shrink_features?

### ISSUE THREAD

**Issue by lubin2022** [DerrickXuNu/OpenCOOD#103]
Thanks for you excellent work before, I have a question about the shrink_features. As we know, before the fision, the features will go through the shrink_conv module to reduce memory. The shape of the tensor after the shrink_conv module are (N, C, H, W), the question is that what's the N satand for? As I set the max_cav to 5 in the yaml file, but I found that the N will be larger than 5. So I will appreciate it if you can explain that.

**Comment by DerrickXuNu** [comment]
Thanks for using Opencood. The N is actually batch_size multiplied with number of agents, which can be larger than 5. This dimension will be split into (B, L) later.
