### ISSUE TITLE
Depth information

### ISSUE THREAD

**Issue by sidiangongyuan** [DerrickXuNu/OpenCOOD#109]
Does OPV2V has any depth information ?

**Comment by DerrickXuNu** [comment]
Yes, you can use the log replay tool to retrieve the depth information by attaching depth sensor.

**Comment by patrickpjiang** [comment]
Hello, I attempted to use log replay to obtain depth images, but I'm encountering issues while creating the depth camera class. Is it possible to directly access the corresponding depth images within the OPV2V datasets? (trying to implement CoCa3D)

**Comment by sidiangongyuan** [comment]
> Hello, I attempted to use log replay to obtain depth images, but I'm encountering issues while creating the depth camera class. Is it possible to directly access the corresponding depth images within the OPV2V datasets? (trying to implement CoCa3D)

I gave up on using a depth sensor to get depth, which is not available in other real datasets.

**Comment by sidiangongyuan** [comment]
> Yes, you can use the log replay tool to retrieve the depth information by attaching depth sensor.

Thank you for your reply.
