### ISSUE TITLE
a subset of dataset

### ISSUE THREAD

**Issue by ChunmianLin** [DerrickXuNu/OpenCOOD#11]
Hi, thanks for your great job. But the dataset is too large to perform validation experiments in my own computer. Could you please divide the dataset into several subsets, so as to download? For example, 73 scenario can be grouped into 4 folds or more.
Thanks a lot.

**Comment by DerrickXuNu** [comment]
Hi, thanks for your interest. I will split the large zip files into small sub-file so each single one won't exceed 500mb. In this way, people can avoid the issue downloading the large file. Will that solve your problem?

**Comment by ChunmianLin** [comment]
Thanks, it is OK. And still, we can access the download link from the project website?

**Comment by DerrickXuNu** [comment]
Yes, it will be the same link. I already upload train and test_culver_city, please have a look

**Comment by DerrickXuNu** [comment]
Also, please have a look at the updated readme to see how to use those chunked files

**Comment by ChunmianLin** [comment]
Thanks. Where the validation chunk files?

**Comment by DerrickXuNu** [comment]
still uploading

**Comment by ChunmianLin** [comment]
Thanks. I am downloading the data...

**Comment by ChunmianLin** [comment]
There seems some error occurred when I extract the compressed the merged file.

**Comment by ChunmianLin** [comment]
![Screenshot from 2022-03-22 16-06-05](https://user-images.githubusercontent.com/53289159/159435306-2a5502eb-35d2-416a-a44c-223cb2543220.png)
what is the problem?

**Comment by ChunmianLin** [comment]
The train data is normal, and the chunks can be merged into a .zip file and extracted. Maybe the test data needs to uploaded, again. Thanks

**Comment by ChunmianLin** [comment]
The test data has downloaded and extracted successfully now, thanks.

**Comment by DerrickXuNu** [comment]
Hi, the validation chunks are also uploaded, have fun!

**Comment by ChunmianLin** [comment]
It is ok! And where is the updated downloading link, still in the google drive? Thanks.---- Replied Message ----FromRunsheng ***@***.***>Date03/22/2022 00:52 ***@***.***> ***@***.******@***.***>SubjectRe: [DerrickXuNu/OpenCOOD] a subset of dataset (Issue #11)
Hi, thanks for your interest. I will split the large zip files into small sub-file so each single one won't exceed 500mb. In this way, people can avoid the issue downloading the large file. Will that solve your problem?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DerrickXuNu/OpenCOOD/issues/11#issuecomment-1074153180",
"url": "https://github.com/DerrickXuNu/OpenCOOD/issues/11#issuecomment-1074153180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
