### ISSUE TITLE
Multi-agents

### ISSUE THREAD

**Issue by shaojiabing** [DerrickXuNu/OpenCOOD#111]
During the training or inference process, how to modify the performance of each vehicle to simulate the different computing capabilities of different vehicles in reality?

**Comment by DerrickXuNu** [comment]
Can you be more specific? Do you mean one vehicle is using a large model and the other uses a small one?

**Comment by shaojiabing** [comment]
yes

**Comment by DerrickXuNu** [comment]
You can split the tensor [B, N, H, W, C] to [B, N1, H, W, C] and [B, N2, H, W, C] and then send the two tensors to different models.

**Comment by shaojiabing** [comment]
thank you!
