### ISSUE TITLE
About No Fusion

### ISSUE THREAD

**Issue by shaojiabing** [DerrickXuNu/OpenCOOD#115]
Hello,firstly thank you for the work you do！I have two questions.
The first one: Is there a way to get no fusion results for intermediate methods？
The second one: For the same dataset, are the no fusion results obtained by using the intermediate method and the late method the same?
I would be grateful if you could answer me.

**Comment by DerrickXuNu** [comment]
Thanks for using Opencood. 

1) Yes,  a hacky way to do this is to change this for loop https://github.com/DerrickXuNu/OpenCOOD/blob/54e70314272b43ebd3e1c7c21ef01128ba670bde/opencood/data_utils/datasets/basedataset.py#L240 to only keep the ego vehicle.
2) It is based on late fusion.

**Comment by ncut2020tjw** [comment]
> Thanks for using Opencood.
> 
> 1. Yes,  a hacky way to do this is to change this for loop https://github.com/DerrickXuNu/OpenCOOD/blob/54e70314272b43ebd3e1c7c21ef01128ba670bde/opencood/data_utils/datasets/basedataset.py#L240
>     to only keep the ego vehicle.
> 2. It is based on late fusion.

Excuse me, how should I modify this loop? Could you tell me more about it in detail? I would be grateful if you could answer me.

**Comment by eyabesbes** [comment]
> > Thanks for using Opencood.
> > 
> > 1. Yes,  a hacky way to do this is to change this for loop https://github.com/DerrickXuNu/OpenCOOD/blob/54e70314272b43ebd3e1c7c21ef01128ba670bde/opencood/data_utils/datasets/basedataset.py#L240
> >    
> >    to only keep the ego vehicle.
> > 2. It is based on late fusion.
> 
> Excuse me, how should I modify this loop? Could you tell me more about it in detail? I would be grateful if you could answer me.

Hi,
I'm also working on the same thing, and I'm wondering if you managed to modify the loop mentioned in your previous message. If so, could you please provide more details on how to modify it? I would greatly appreciate your response.

**Comment by ChengChen2020** [comment]
I think another hacky way is to set `max_cav` to 1 in configuration file, then only the ego vehicle data is included when building the dataset.
