### ISSUE TITLE
Error saving visualization results

### ISSUE THREAD

**Issue by githigher** [DerrickXuNu/OpenCOOD#119]
Why do I get the following error when I try to save a visual image：
<img width="1106" alt="error" src="https://github.com/DerrickXuNu/OpenCOOD/assets/113331595/be8c7130-996e-40bf-be4d-519098382526">
<img width="395" alt="error2" src="https://github.com/DerrickXuNu/OpenCOOD/assets/113331595/aeb7cdd7-4c58-4c6e-972d-7175079b814e">
And when the program terminates, it will continue to occupy the graphics memory of my graphics card.
Here are my commands:
` CUDA_VISIBLE_DEVICES=1 python opencood/tools/inference.py --model_dir /home/coop/gyt/OpenCOOD-main/model_dir/60_base/voxel_test/ --fusion_method intermediate --save_vis`

**Comment by 2429993608** [comment]
"I have a similar question. Have you resolved it?"

**Comment by 2429993608** [comment]
"I have a similar question. Have you resolved it?"

**Comment by 2429993608** [comment]
> Why do I get the following error when I try to save a visual image： <img alt="error" width="1106" src="https://private-user-images.githubusercontent.com/113331595/291906958-be8c7130-996e-40bf-be4d-519098382526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjcyOTMsIm5iZiI6MTcwNDM2Njk5MywicGF0aCI6Ii8xMTMzMzE1OTUvMjkxOTA2OTU4LWJlOGM3MTMwLTk5NmUtNDBiZi1iZTRkLTUxOTA5ODM4MjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMTE2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmZiMDAyODIxMWFhMmRhMDU2OWQxODJjMjBiMjdkYjZjYTAzODc4ZjUwNzQ3NTI0MjFiZjVhMDM4NGQ3OTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6uzQhIZjA5f4BZ5Uj7oAlF5dtxhnSUue_D43QwXT1yI"> <img alt="error2" width="395" src="https://private-user-images.githubusercontent.com/113331595/291906980-aeb7cdd7-4c58-4c6e-972d-7175079b814e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjcyOTMsIm5iZiI6MTcwNDM2Njk5MywicGF0aCI6Ii8xMTMzMzE1OTUvMjkxOTA2OTgwLWFlYjdjZGQ3LTRjNTgtNGM2ZS05NzJkLTcxNzUwNzliODE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMTE2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTRhMDc2ODg2MGM4ZTIwMGMyNWQ2ZDA1NDA0OWU5ZGZlNDlmZTNmYzE2YTNkZjY2YTExZDc5NWU0NjE3MzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RovhH5EmEI4P1IGGit5WaAL9OKalCwnuEcYNXnw-6eI"> And when the program terminates, it will continue to occupy the graphics memory of my graphics card. Here are my commands: ` CUDA_VISIBLE_DEVICES=1 python opencood/tools/inference.py --model_dir /home/coop/gyt/OpenCOOD-main/model_dir/60_base/voxel_test/ --fusion_method intermediate --save_vis`

"I have a similar question. Have you resolved it?"

**Comment by eyabesbes** [comment]
> Why do I get the following error when I try to save a visual image： <img alt="error" width="1106" src="https://private-user-images.githubusercontent.com/113331595/291906958-be8c7130-996e-40bf-be4d-519098382526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODMzNDMsIm5iZiI6MTcxMzI4MzA0MywicGF0aCI6Ii8xMTMzMzE1OTUvMjkxOTA2OTU4LWJlOGM3MTMwLTk5NmUtNDBiZi1iZTRkLTUxOTA5ODM4MjUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxNTU3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGI4OTdkMTcxMjYzMjFiMjMyZWUwMzYyZmFmOWMxMmM3YWNhZmZkODY4NDMzMTc2YjEyOTQ2NmI3N2NiMmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MLPNRd-dnfl67muTsouktfy_XC5nRtfInWM6CkKb3s8"> <img alt="error2" width="395" src="https://private-user-images.githubusercontent.com/113331595/291906980-aeb7cdd7-4c58-4c6e-972d-7175079b814e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODMzNDMsIm5iZiI6MTcxMzI4MzA0MywicGF0aCI6Ii8xMTMzMzE1OTUvMjkxOTA2OTgwLWFlYjdjZGQ3LTRjNTgtNGM2ZS05NzJkLTcxNzUwNzliODE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxNTU3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzgyMmNiYTcyMTM4MTljZjA1NzEwMTk3OWMxMWE0Y2Q0NjNmMTYyNWI2NDNmZmQ3ZTY5MDc1ZmZlMTFiOGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Md98e8TsjtivTr8NDOXXFdVHiAUiTBSR_2IR2s9jIsE"> And when the program terminates, it will continue to occupy the graphics memory of my graphics card. Here are my commands: ` CUDA_VISIBLE_DEVICES=1 python opencood/tools/inference.py --model_dir /home/coop/gyt/OpenCOOD-main/model_dir/60_base/voxel_test/ --fusion_method intermediate --save_vis`

Hi,
I have been facing the issue?

have you finally resolved it  or did you just use -- save_npy?
