### ISSUE TITLE
Models provided in the link seems broken

### ISSUE THREAD

**Issue by drowning-in-codes** [DerrickXuNu/OpenCOOD#123]
Thanks for your codebase!
I tested the model provided in [PointPillar_fcooper](https://drive.google.com/file/d/1CjXu9Y2ZTzJA6Oo3hnqFhbTqBVKq3mQb/view?usp=sharing), but the inference speed seems strangely slow and the result is weird.
I run the command below to show the result, it seems like pred_boxs in red are different from gt_box in green.
`python opencood/tools/inference.py --model_dir "./opencood/logs/pointpillar_fcooper"  --fusion_method "intermediate"  --save_vis`
![image](https://github.com/DerrickXuNu/OpenCOOD/assets/60743790/ff19a109-36d2-4926-a64b-ad230dd88aba)
and the ap is also weird.
![image](https://github.com/DerrickXuNu/OpenCOOD/assets/60743790/ed4f58b0-506c-4129-9d6f-0fc98d213225)
I think there's something wrong with this model or is there anything wrong with me?

**Comment by 2429993608** [comment]
"How is your visualization configured, and why am I unable to visualize it?"

**Comment by drowning-in-codes** [comment]
> "How is your visualization configured, and why am I unable to visualize it?"

I don't know your setup, but I used remote server for infer and found that it needs an additional settings in the remote server to visualize(Iit's related to VNC and some stuff).
I notice that [open3d](https://github.com/isl-org/Open3D) is used to visualize and it needs to create a GUI window which is not supported in non-a GUI remote server without additional settings.So I train on remote and inference with visualization local.

**Comment by 2429993608** [comment]
ok~ Thank you very much for your reply.

**Comment by 2429993608** [comment]
> > "How is your visualization configured, and why am I unable to visualize it?"
> 
> I don't know your setup, but I used remote server for infer and found that it needs an additional settings in the remote server to visualize(Iit's related to VNC and some stuff). I notice that [open3d](https://github.com/isl-org/Open3D) is used to visualize and it needs to create a GUI window which is not supported in non-a GUI remote server without additional settings.So I train on remote and inference with visualization local.

ok~ Thank you very much for your reply.

**Comment by 2429993608** [comment]
> > "How is your visualization configured, and why am I unable to visualize it?"
> 
> I don't know your setup, but I used remote server for infer and found that it needs an additional settings in the remote server to visualize(Iit's related to VNC and some stuff). I notice that [open3d](https://github.com/isl-org/Open3D) is used to visualize and it needs to create a GUI window which is not supported in non-a GUI remote server without additional settings.So I train on remote and inference with visualization local.

Hello, could you please tell me about your environment configuration? My configuration is as follows:
pytorch 1.12.0
Spconv 2.x (spconv-cu102-2.3.6)
open3d 0.17.0

**Comment by drowning-in-codes** [comment]
> > > "How is your visualization configured, and why am I unable to visualize it?"
> > 
> > 
> > I don't know your setup, but I used remote server for infer and found that it needs an additional settings in the remote server to visualize(Iit's related to VNC and some stuff). I notice that [open3d](https://github.com/isl-org/Open3D) is used to visualize and it needs to create a GUI window which is not supported in non-a GUI remote server without additional settings.So I train on remote and inference with visualization local.
> 
> Hello, could you please tell me about your environment configuration? My configuration is as follows: pytorch 1.12.0 Spconv 2.x (spconv-cu102-2.3.6) open3d 0.17.0


I just follow the installation guide， clone the repo, and type the command below, so the dependency is totally the same as in `equirements.txt`, and python version is 3.7.
`conda env create -f environment.yml
conda activate opencood
python setup.py develop
pip install -r requirements.txt
`

**Comment by drowning-in-codes** [comment]
well, it looks like I have got it wrong.
