### ISSUE TITLE
How to use dair-v2x in opencood ? 

### ISSUE THREAD

**Issue by sidiangongyuan** [DerrickXuNu/OpenCOOD#127]

**Comment by RadetzkyLi** [comment]
You need to rewrite the code related to data loading (e.g., `BaseDataset`). Luckily, I found the repo https://github.com/yifanlu0227/HEAL had done this well, which supports OPV2V, V2XSet, V2XSim 2.0 and DAIR-V2X-C.

**Comment by sidiangongyuan** [comment]
> You need to rewrite the code related to data loading (e.g., `BaseDataset`). Luckily, I found the repo https://github.com/yifanlu0227/HEAL had done this well, which supports OPV2V, V2XSet, V2XSim 2.0 and DAIR-V2X-C.

OK， thank you
