### ISSUE TITLE
Questions about single view visualization before/After collaboration

### ISSUE THREAD

**Issue by eyabesbes** [DerrickXuNu/OpenCOOD#133]
Hi,

I'm currently working on optimizing data sharing among autonomous vehicles (AVs), and I came across your work, which I will be using as a reference. So far, I have successfully replayed the scenarios and visualized the data in Carla. Now, I want to visualize the LiDAR data of each agent after feature extraction, both before and after fusion, in order to compare each agent's view before and after collaboration.

However, I noticed that when I try to visualize the data using models that utilize early fusion, I only get the data of the ego vehicle, and all the other data from the other AVs is projected onto the ego vehicle's data. Should I use the LateFusion Dataset (even though I'm using an early fusion model) to visualize the data of each agent instead of seeing only one agent's data?

Let's consider the scenario where I want to see the view of each agent before collaboration using only PointPillars as a backbone for feature extraction. In this case, what should I do exactly? 

And as for the scenario where I want to see each agent's view after collaboration using an early fusion method (e.g., Point_Pillar_early_fusion), what should I do exactly in this case?

**Comment by MinkyoungCho** [comment]
Hey, have you resolved this issue? If so, could you share how we can visualize them (after/before) ?
