### ISSUE TITLE
About timestamps in naming PCD files

### ISSUE THREAD

**Issue by shaojiabing** [DerrickXuNu/OpenCOOD#134]
Hello, thank you very much for your great work. The naming of. pcd files in the opv2v and v2xset datasets is done using timestamps (such as 000068. pcd). The timestamps of the two pcds differ by 2. May I ask if the timestamps are in seconds or 0.1 seconds

**Comment by RadetzkyLi** [comment]
As written in their papers, the data is "streamed at 20Hz but saved at 10Hz". So, the time gap between timestamps "000068" and "000070" is 0.1 second. The timestamp originates from CARLA and increase 1 after a simulation timestep (0.05s in OPV2V and V2XSet).

**Comment by shaojiabing** [comment]
> As written in their papers, the data is "streamed at 20Hz but saved at 10Hz". So, the time gap between timestamps "000068" and "000070" is 0.1 second. The timestamp originates from CARLA and increase 1 after a simulation timestep (0.05s in OPV2V and V2XSet).

Thank you very much
