### ISSUE TITLE
About cav_lidar_range and GT_range

### ISSUE THREAD

**Issue by shaojiabing** [DerrickXuNu/OpenCOOD#139]
Thanks for your great work!
I have a question about the radar range：
In OpenCOOD, there is a “cav_lidar_range” in models' config.yaml, as follow:
    lidar_range: &id004
    - -140.8
    - -38.4
    - -3
    - 140.8
    - 38.4
    - 1
And there is GT_RANGE at 'OpenCOOD/opencood/data_utils/datasets/__init__.py', as follow:
GT_RANGE = [-140, -40, -3, 140, 40, 1]

The "cav_lidar_range" is used to segment the point cloud files of vehicles and to merge the point clouds of multiple vehicles within this range, followed by recognition within this range to obtain the vehicle recognition bounding box.
"GT_RANGE" is used to generate the actual vehicle coordinate frames. 
Eventually, the actual vehicle coordinate frames are compared with the vehicle recognition bounding boxes to obtain the IOU.

Is it possible to modify both "cav_lidar_range" and "GT_RANGE" to other ranges that I want, and then train, ultimately for inference?

**Comment by shaojiabing** [comment]
Can I use your pre-trained model for inference on the model I've modified with a different range?

**Comment by DerrickXuNu** [comment]
Yes, you can set whatever range you for training. But for inference, it should stay the same for fairness.
