### ISSUE TITLE
Why is the result evaluation of the latest v2vnet model all 0 

### ISSUE THREAD

**Issue by zhangheyi-1** [DerrickXuNu/OpenCOOD#14]
I use the validate test set to run the latest v2vnet model, and the evaluation results are all 0. Why does this result occur?

**Comment by DerrickXuNu** [comment]
What is your spconv version? What is the command you running the test? And did you change the yaml file?

**Comment by zhangheyi-1** [comment]
Spconv version is 1.2.1

The command is 
`python /home/system/OpenCDA/Opencood/opencood/tools/inference.py --model_dir  /home/system/OpenCDA/Opencood/point_pillar_v2vnet/v2vnet --fusion_method intermediate`
The configuration file modifies the path of the test set. I didn't have this problem when I tested other models.

**Comment by zhangheyi-1** [comment]
Ok, I will try it latter, thank you for your reply.

**Comment by DerrickXuNu** [comment]
Hi, please try again, I have uploaded the new one

**Comment by zhangheyi-1** [comment]
I tried it again just now. There is no problem. Thanks for your assistance.
