### ISSUE TITLE
ego cavs are not in the ground truth, will it  affect the acc?

### ISSUE THREAD

**Issue by drowning-in-codes** [DerrickXuNu/OpenCOOD#141]
Hi, great thanks to your code base! I'm a bit confused about some settings in the code.
In the opv2v data yaml files, vehicles are objects that collaborative perception will detect(i.e. gtbox), and I find that there are no ego and support cavs. 
But the predicted result will usually output the ego and support cavs bbox, so there is always a mismatch. Will it affect the iou or acc? Thanks again for your great work and looking forward to your reply.

**Comment by xiaojianyuyong** [comment]
Same problem, have you solved this problem?

**Comment by DerrickXuNu** [comment]
Yes, it will actually influence the AP a bit. But since all the methods use the same setting, i guess it is fair? You are welcome to remove those or add gt for it.
