### ISSUE TITLE
Intermediate fusion baseline

### ISSUE THREAD

**Issue by CatOneTwo** [DerrickXuNu/OpenCOOD#19]
Hi, I noticed that "To evaluate the proposed pipeline, we only need to add the Compression, Sharing, and Attention (CSA) module to the existing network architecture" in the paper, so do you add "Metadata Sharing" in the intermediate fusion or other fusion baselines?
 
And does the task is 3D object detection or 2D object detection, because there is no visualization in the paper, I'm not very clear.

**Comment by DerrickXuNu** [comment]
do you add "Metadata Sharing" in the intermediate fusion or other fusion baselines?
--> yes, in the code, I assume the metadata sharing is a well-synchronized process, so each cav knows the ego vehicle's pose at the very begining.
3D or 2D:
It is 3D object detection task.
