### ISSUE TITLE
Installation Spconv1.2.1

### ISSUE THREAD

**Issue by CatOneTwo** [DerrickXuNu/OpenCOOD#20]
Hi, the installation needs Spconv 1.2.1, but the website you provided (https://github.com/traveller59/spconv/tree/v1.2.1) only supports the spconv 2.1.21 now, it has discarded the spconv 1.2.1 . I have followed the instructions in v1.2.1, but the installed spconv is still 2.1.21.

With spconv 2.1.21, the code cannot run. So could you please provide spconv 1.2.1 wheel, thank you!

**Comment by DerrickXuNu** [comment]
Check their 1.2.1 branch please.

https://github.com/traveller59/spconv/tree/v1.2.1

**Comment by DerrickXuNu** [comment]
Yes you need to checkout to that branch
