### ISSUE TITLE
Hard to download the dataset

### ISSUE THREAD

**Issue by PointsCoder** [DerrickXuNu/OpenCOOD#22]
Thanks for your excellent work! I met a problem downloading the dataset from google drive with commands. Here is the error information:

![image](https://user-images.githubusercontent.com/28640612/171639299-3800f325-9304-4f62-9b44-f74a283e1e86.png)

I guess the data has been downloaded too many times so Google has blocked the link. It's still available to download from a web browser but it's not quite convenient for me. Are there any other ways of downloading this dataset (e.g. dropbox)?

**Comment by DerrickXuNu** [comment]
Thanks for use OPV2V!  Are you able to download the chunks instead of the whole zip?
