### ISSUE TITLE
url of Cooper using PointPillar Backbone doesn't exist

### ISSUE THREAD

**Issue by xieqi1996** [DerrickXuNu/OpenCOOD#25]
The pretrained url of the early fusion strategy(Cooper) using PointPillar Backbone didn't exist, Could you please upload it again?

**Comment by DerrickXuNu** [comment]
Sorry to hear that. I will update the readme soon, but for now, can you use this linke directly? https://drive.google.com/file/d/1H1pmY6-0IH87Z87PRzy60_lay426NavP/view?usp=sharing

**Comment by xieqi1996** [comment]
> Sorry to hear that. I will update the readme soon, but for now, can you use this linke directly? https://drive.google.com/file/d/1H1pmY6-0IH87Z87PRzy60_lay426NavP/view?usp=sharing



> Sorry to hear that. I will update the readme soon, but for now, can you use this linke directly? https://drive.google.com/file/d/1H1pmY6-0IH87Z87PRzy60_lay426NavP/view?usp=sharing

Thank you! I have downloaded it successfully!
