### ISSUE TITLE
Question about accuracy and bandwidth test

### ISSUE THREAD

**Issue by ellen19967** [DerrickXuNu/OpenCOOD#29]
Hello, may I ask how to test no fusion accuracy and bandwidth required for data transmission

**Comment by DerrickXuNu** [comment]
Please refer to this issue  ttps://github.com/DerrickXuNu/OpenCOOD/issues/8 for nu fusion.
Data transmission size: This need to be calculated by hand. You should use the HWC of the transmitted feature map to get the bandwidth. Specifically, data size (MB) = H x W x C x 4 / 1000000

**Comment by ellen19967** [comment]
Thanks for your help.
