### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by CatOneTwo** [DerrickXuNu/OpenCOOD#31]
Hi, I noticed that data augmentation is used in early fusion and late fusion, why the intermediate fusion doesn't use data augmentation? Thank you~

**Comment by DerrickXuNu** [comment]
nice catch. This is because data augmentation is usually done on the point-cloud level, and when you rotate/translate the point cloud, the global gt bound box needs to be moved together. But in intermediate fusion, this is hard to achieve. I think this should be a good point for research.

**Comment by CatOneTwo** [comment]
I get it~
I have another question. I noticed that the code aggregates all bounding boxes of the collaborative vehicle as ground truth, so which is the ground truth of no fusion methods? Aggregation bounding boxes or ego bounding boxes only? thank you~

**Comment by DerrickXuNu** [comment]
During training, it is its own bounding box. During testing, it is the aggregated bounding box.
