### ISSUE TITLE
SECOND and PointPillars implementation

### ISSUE THREAD

**Issue by ChunmianLin** [DerrickXuNu/OpenCOOD#32]
Hi, I check the implementation of SECOND or PointPillar is slightly different from the in other framework (i.e., OpenCOOD), such as proposal layer. dense head and roi head. What is your concern about it?

**Comment by DerrickXuNu** [comment]
Sorry, I didn't get you. Do you mean PointPillar official implementation is different from OpenCood?

**Comment by ChunmianLin** [comment]
Yes, the proposal layer and anchor generation process seem to be removed  in the OpenCOOD.

**Comment by DerrickXuNu** [comment]
No, it is not removed. I used OpenPCDet's implementation and please carefully check the codes.

**Comment by DerrickXuNu** [comment]
https://github.com/DerrickXuNu/OpenCOOD/blob/42776d04810334a8a55f7abb8dfaf848ce9c3359/opencood/data_utils/post_processor/voxel_postprocessor.py#L29

**Comment by ChunmianLin** [comment]
Thanks. But I do not find the parameter settings about dense head or roi head in the config.yaml file.

**Comment by ChunmianLin** [comment]
Thanks. But I do not find the parameter settings about dense head or roi head in the config.yaml file.

**Comment by DerrickXuNu** [comment]
For second and pointpillar, I believe they are one-stage detector, so there should be no roi head. For dense head, I utilized 2 simple 3x3 convolution to get classification/regression.

**Comment by ChunmianLin** [comment]
many thanks, I got it.
