### ISSUE TITLE
coordinate alignment

### ISSUE THREAD

**Issue by ChunmianLin** [DerrickXuNu/OpenCOOD#33]
Hi, does the point cloud coordinate of OPV2V dataset unify the setting in OpenPCDet, i.e., right-hand rule (x:forward, y,: left and z: up), anticlock-wise and zero angle located at x-axis?

**Comment by ChunmianLin** [comment]
Thanks, so do you perform the transformation from openpcdet to lidar coordiante?

**Comment by DerrickXuNu** [comment]
No. Data processing part is done with my own implementation. I just integrate the model part from openpcdet.

**Comment by ChunmianLin** [comment]
thanks.

**Comment by ChunmianLin** [comment]
Excuse me, if I want to transform the coordinate in opencood into the openpcdet format, how should I do?

**Comment by DerrickXuNu** [comment]
You can transform the point cloud to the openpcdet coordinates when loading the pcd files

**Comment by ChunmianLin** [comment]
Thanks. What does the 'record_len' mean, and what is the function of 'regroup' in the self.attn.py?
