### ISSUE TITLE
Map data of OPV2V.

### ISSUE THREAD

**Issue by zqzqz** [DerrickXuNu/OpenCOOD#35]
Given a scenario in OPV2V like `test/2021_08_18_19_48_05`, how can I know which map the simulation is using? I would like to test some algorithms that require an input of map information. The map information can be in Carla format.

Thanks!

**Comment by DerrickXuNu** [comment]
Hi, you can check the branch feature/log_replay,  under the log_relay folder, we provides a lot of codes about how to retrieve the map information from the dataset. But a quick answer to your question:

TOWN_DICTIONARY = {
    '2021_08_20_21_48_35': 'Town06',
    '2021_08_18_19_48_05': 'Town06',
    '2021_08_20_21_10_24': 'Town06',
    '2021_08_21_09_28_12': 'Town06',
    '2021_08_22_07_52_02': 'Town05',
    '2021_08_22_09_08_29': 'Town05',
    '2021_08_22_21_41_24': 'Town05',
    '2021_08_23_12_58_19': 'Town05',
    '2021_08_23_15_19_19': 'Town04',
    '2021_08_23_16_06_26': 'Town04',
    '2021_08_23_17_22_47': 'Town04',
    '2021_08_23_21_07_10': 'Town10HD',
    '2021_08_23_21_47_19': 'Town10HD',
    '2021_08_24_07_45_41': 'Town10HD',
    '2021_08_24_11_37_54': 'Town07',
    '2021_08_24_20_09_18': 'Town04',
    '2021_08_24_20_49_54': 'Town04',
    '2021_08_24_21_29_28': 'Town04',
    '2021_08_16_22_26_54': 'Town06',
    '2021_08_18_09_02_56': 'Town06',
    '2021_08_18_18_33_56': 'Town06',
    '2021_08_18_21_38_28': 'Town06',
    '2021_08_18_22_16_12': 'Town06',
    '2021_08_18_23_23_19': 'Town06',
    '2021_08_19_15_07_39': 'Town06',
    '2021_08_20_16_20_46': 'Town06',
    '2021_08_20_20_39_00': 'Town06',
    '2021_08_20_21_00_19': 'Town06',
    '2021_08_21_09_09_41': 'Town06',
    '2021_08_21_15_41_04': 'Town05',
    '2021_08_21_16_08_42': 'Town05',
    '2021_08_21_17_00_32': 'Town05',
    '2021_08_21_21_35_56': 'Town05',
    '2021_08_21_22_21_37': 'Town05',
    '2021_08_22_06_43_37': 'Town05',
    '2021_08_22_07_24_12': 'Town05',
    '2021_08_22_08_39_02': 'Town05',
    '2021_08_22_09_43_53': 'Town05',
    '2021_08_22_10_10_40': 'Town05',
    '2021_08_22_10_46_58': 'Town06',
    '2021_08_22_11_29_38': 'Town06',
    '2021_08_22_22_30_58': 'Town05',
    '2021_08_23_10_47_16': 'Town04',
    '2021_08_23_11_06_41': 'Town05',
    '2021_08_23_11_22_46': 'Town04',
    '2021_08_23_12_13_48': 'Town05',
    '2021_08_23_13_10_47': 'Town05',
    '2021_08_23_16_42_39': 'Town04',
    '2021_08_23_17_07_55': 'Town04',
    '2021_08_23_19_27_57': 'Town10HD',
    '2021_08_23_20_47_11': 'Town10HD',
    '2021_08_23_22_31_01': 'Town10HD',
    '2021_08_23_23_08_17': 'Town10HD',
    '2021_08_24_09_25_42': 'Town07',
    '2021_08_24_09_58_32': 'Town07',
    '2021_08_24_12_19_30': 'Town07',
    '2021_09_09_13_20_58': 'Town03',
    '2021_09_09_19_27_35': 'Town01',
    '2021_09_10_12_07_11': 'Town04',
    '2021_09_09_23_21_21': 'Town03',
    '2021_08_21_17_30_41': 'Town05',
    '2021_08_22_13_37_16': 'Town06',
    '2021_08_22_22_01_17': 'Town05',
    '2021_08_23_10_51_24': 'Town05',
    '2021_08_23_13_17_21': 'Town05',
    '2021_08_23_19_42_07': 'Town10HD',
    '2021_09_09_22_21_11': 'Town02',
    '2021_09_11_00_33_16': 'Town10HD',
    '2021_08_18_19_11_02': 'Town06'
}

**Comment by zqzqz** [comment]
Thank you. That is exactly what I need.
