### ISSUE TITLE
No module named 'opencood.utils.box_overlaps'

### ISSUE THREAD

**Issue by JonathanLi19** [DerrickXuNu/OpenCOOD#36]
Hi! When I tried to train a model ,it shows a model_notfound_error: 
![屏幕截图 2022-08-05 134000](https://user-images.githubusercontent.com/73473823/183009069-84f1e06d-efe5-4daf-8abc-5a11211bbbc9.png)
However, when  I tried to import it in a python console,it can be imported:
![屏幕截图 2022-08-05 134156](https://user-images.githubusercontent.com/73473823/183009267-71afe0b9-85e9-4c9d-beda-fd199529e72c.png)
How can I fix this problem? thank you!

**Comment by DerrickXuNu** [comment]
Did you run the last step in the installation guidance? And did you run python setup.py develop?

**Comment by JonathanLi19** [comment]
> Did you run the last step in the installation guidance? And did you run python setup.py develop?

Yes, I have already run both of them

**Comment by DerrickXuNu** [comment]
Are you running the command under the root of OpemCOOd?

**Comment by JonathanLi19** [comment]
> Are you running the command under the root of OpemCOOd?

yes

**Comment by DerrickXuNu** [comment]
This is wired. I have not encountered this before. Did you activate the environment? Can you do testing? Did you try to reinstall the environment?

**Comment by JonathanLi19** [comment]
> This is wired. I have not encountered this before. Did you activate the environment? Can you do testing? Did you try to reinstall the environment?

ok thank you. I will try to reinstall the whole environment. maybe I made some mistakes during installation

**Comment by JonathanLi19** [comment]
problem solved! thank you ( something wrong happened when I add cmake executables to PATH)

**Comment by yxlbit** [comment]
> > This is wired. I have not encountered this before. Did you activate the environment? Can you do testing? Did you try to reinstall the environment?
> 
> ok thank you. I will try to reinstall the whole environment. maybe I made some mistakes during installation

I encounterd this problem. Could you tell me how you solve this? Thank you

**Comment by JonathanLi19** [comment]
> > > This is wired. I have not encountered this before. Did you activate the environment? Can you do testing? Did you try to reinstall the environment?
> > 
> > 
> > ok thank you. I will try to reinstall the whole environment. maybe I made some mistakes during installation
> 
> I encounterd this problem. Could you tell me how you solve this? Thank you

At that time, I first installed opencood on a machine without gpus and then turned to a machine with gpus. You should try install it all on one machine with gpu. Hope this can help you.

**Comment by yxlbit** [comment]
Thank you

**Comment by yxlbit** [comment]
> 
Sorry to disturb you again. I Installed opencood in a machine with gpu. However, it still appear this problem. I config the environment according to the environment.yml. If you are convenient, can you add me webchat. wbchat:YXL6009202185

**Comment by hitmachineWu** [comment]
Don't  worry, this problem was caused from the lack of essential conda enviroment set up. Try to run the command
at OpenCood directory more than once till no compile error was reported. 
 `python setup.py develop`

**Comment by huanghelouzi** [comment]
run the code in shell
```shell
python opencood/utils/setup.py build_ext --inplace
```
