### ISSUE TITLE
How is the bandwidth of Attentive Fusion (backbone is VoxelNet) 576.71 calculated before compression？

### ISSUE THREAD

**Issue by zllxot** [DerrickXuNu/OpenCOOD#38]
Hi！I learned from [issue #29](https://github.com/DerrickXuNu/OpenCOOD/issues/29) that the bandwidth is calculated by `H×W×C×4/100,0000`.
Then I run voxel_net_intermediate.py and debug to see that the shape of the feature before compression is [5, 128, 200, 704]：
![image](https://user-images.githubusercontent.com/109151298/187442532-a5d87ce1-b06e-4522-b494-a167d76ee25d.png)
but `200 ×704×128×4/100,0000≈72.08` instead of 576.71, what is the problem

**Comment by DerrickXuNu** [comment]
72.08MB= 576Mb

**Comment by zllxot** [comment]
> 72.08MB= 576Mb

ok, thanks for your help.
