### ISSUE TITLE
Can I test this codebase with CPU only? 

### ISSUE THREAD

**Issue by MinkyoungCho** [DerrickXuNu/OpenCOOD#41]
Would like to ask if we can run this codebase on CPU environment (even if we hurt the latency).

According to the installation manual, below instruction is written on the page. 
`Adequate GPU. A minimum of 6GB gpu is recommended.`
So, just curious, running with CPU only is possible but not recommended.

**Comment by DerrickXuNu** [comment]
I think you can run on CPU. Just try it, it should work
