### ISSUE TITLE
CUDA memory usage varies

### ISSUE THREAD

**Issue by yifanlu0227** [DerrickXuNu/OpenCOOD#42]
Hi runsheng,

Thanks for your framework again! One thing bothers me that I found that the CUDA memory usage varies a lot at runtime.  Is there any solution to fix the memory usage? Then my program would not be preempted by others :). 

Thank you in advance.

**Comment by DerrickXuNu** [comment]
Hi Yifan, is it during training or inference?

**Comment by yifanlu0227** [comment]
during the training phase
