### ISSUE TITLE
Cython modules are not compiled automatically

### ISSUE THREAD

**Issue by zqzqz** [DerrickXuNu/OpenCOOD#5]
PYX files, for instance `opencood/utils/box_overlaps.pyx` are not compiled by `setup.py`, which results in import errors.

My fix in `setup.py`
```
from Cython.Build import cythonize

setup(
  ext_modules = cythonize("opencood/utils/box_overlaps.pyx")
)
```

**Comment by DerrickXuNu** [comment]
Hi thanks for using OpenCOOD! 

In the installation guide, the last step indicates you have to run the following command to manually compile the pyx file, did you do that? 

python opencood/utils/setup.py build_ext --inplace

**Comment by zqzqz** [comment]
Hi @DerrickXuNu. I missed that final step. Thank you for helping!
