### ISSUE TITLE
Request pre-trained models

### ISSUE THREAD

**Issue by zllxot** [DerrickXuNu/OpenCOOD#56]
Hi, I noticed that the download url for the Naive Late pre-trained model (backbone is VoxelNet) is unavailable. Could you please upload it again? By the way, can you provide more pre-trained models based on VoxelNet backbone? Thanks!

**Comment by DerrickXuNu** [comment]
Hi, unfortunately, I can't find the naive late VoxelNet model anymore since it is already around 1.5 years ago. But you should be easy to train yourself to get similar number in the paper

**Comment by zllxot** [comment]
OK, thanks for your reply.
