### ISSUE TITLE
cannot import name 'iou3d_nms_cuda' from 'opencood.pcdet_utils.iou3d_nms' (unknown location)

### ISSUE THREAD

**Issue by HuangZhe885** [DerrickXuNu/OpenCOOD#61]
When I try  to  use cia-ssd, I got this mistake
cannot import name 'iou3d_nms_cuda' from 'opencood.pcdet_utils.iou3d_nms' (unknown location)

**Comment by HuangZhe885** [comment]
I followed the installation instructions but did not discover that iou3d nms cuda was produced.

**Comment by HuangZhe885** [comment]
I fixed this issue since the Python and CUDA versions were incompatible.

**Comment by MahdiZaman** [comment]
Hi @HuangZhe885 , can you please provide more details how you solved this issue? What versions of python and cuda versions worked for you?
