### ISSUE TITLE
Is the code of CIA-SSD complete?

### ISSUE THREAD

**Issue by HuangZhe885** [DerrickXuNu/OpenCOOD#63]
Thank you for your great work, I have a Q : Is the code of CIA-SSD complete? I'd want to discuss how D-NMS is implemented.

**Comment by DerrickXuNu** [comment]
Yes, I haven't gotten a chance to look into the problem you mentioned, as I am busy with my internship right now. Are you able to run FPV-RCNN code? Also, this part is implemented by @YuanYunshuang, so Yunshuang, maybe you are the best to help it.

**Comment by HuangZhe885** [comment]
> > Thank you for your great work, I have a Q : Is the code of CIA-SSD complete? I'd want to discuss how D-NMS is implemented.
> 
> Hi, for CIASSD the scores for NMS is rectified with the predicted IOUs as suggested in the paper. You can find more details in the paper.

I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.

**Comment by HuangZhe885** [comment]
> I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.

I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.

**Comment by HuangZhe885** [comment]
> Yes, I haven't gotten a chance to look into the problem you mentioned, as I am busy with my internship right now. Are you able to run FPV-RCNN code? Also, this part is implemented by @YuanYunshuang, so Yunshuang, maybe you are the best to help it.

I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.

**Comment by YuanYunshuang** [comment]
> > Yes, I haven't gotten a chance to look into the problem you mentioned, as I am busy with my internship right now. Are you able to run FPV-RCNN code? Also, this part is implemented by @YuanYunshuang, so Yunshuang, maybe you are the best to help it.
> 
> 
> 
> I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.

If you cannot compile it, it might be caused by the version problem. The newest version was upgraded to higher version. To spconv2 or over PyTorch 1.8. Some cuda code might not pass the compilation with PyTorch over 1.8.

**Comment by HuangZhe885** [comment]
> > > 是的，我没有机会研究你提到的问题，因为我现在正忙于实习。你能运行 FPV-RCNN 代码吗？此外，这部分由@YuanYunshuang，所以云霜，或许你是最能帮助它的人。
> > 
> > 
> > 我不确定这是否是我的错，但 CIA-SSD 和 FPV-RCNN 都不会运行。
> 
> 如果不能编译，可能是版本问题。最新版本已升级到更高版本。到 spconv2 或 PyTorch 1.8 以上。一些 cuda 代码可能无法通过 1.8 以上的 PyTorch 编译。

My spconv version is 2.0, and my pytorch version is 1.8, python =3.7. Additional algorithms can be run, however when these two are executed, an error is reported.
when I run ciassd-early-fusion.yaml,it shows:
`  File "/home/cood/OpenCOOD/opencood/models/sub_modules/mean_vfe.py", line 25, in forward
    voxel_features, voxel_num_points = batch_dict['voxel_features'], \
KeyError: 'voxel_features'`
when I run fpvrcnn_intermediate_fusion.yaml,it shows:
`  File "/home/miniconda3/envs/COOD/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 155, in _conv_forward
    1] == self.in_channels, "channel size mismatch"
AssertionError: channel size mismatch`

**Comment by HuangZhe885** [comment]
> > > Yes, I haven't gotten a chance to look into the problem you mentioned, as I am busy with my internship right now. Are you able to run FPV-RCNN code? Also, this part is implemented by @YuanYunshuang, so Yunshuang, maybe you are the best to help it.
> > 
> > 
> > I'm not sure whether it's my fault, but neither CIA-SSD nor FPV-RCNN will operate.
> 
> If you cannot compile it, it might be caused by the version problem. The newest version was upgraded to higher version. To spconv2 or over PyTorch 1.8. Some cuda code might not pass the compilation with PyTorch over 1.8.


My spconv version is 2.0, and my pytorch version is 1.8, python =3.7. Additional algorithms can be run, however when these two are executed, an error is reported.
when I run ciassd-early-fusion.yaml,it shows:
`  File "/home/cood/OpenCOOD/opencood/models/sub_modules/mean_vfe.py", line 25, in forward
    voxel_features, voxel_num_points = batch_dict['voxel_features'], \
KeyError: 'voxel_features'`
when I run fpvrcnn_intermediate_fusion.yaml,it shows:
`  File "/home/miniconda3/envs/COOD/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 155, in _conv_forward
    1] == self.in_channels, "channel size mismatch"
AssertionError: channel size mismatch`

**Comment by YuanYunshuang** [comment]
You might need to add the corresponding parameter for voxel feature and the correct input feature size in the yaml config file. 
Since I am recently traveling and not able to check the details of the errors but maybe you can try the fpvrcnn branch of this repo https://github.com/YuanYunshuang/OpenCOOD

This is the runnable old version. The recent updates of the official repo have many changes that might not support FPV-RCNN anymore and is not maintained anymore because this model is not very compatible with the other part of the code. And I recommend you to use spconv1.2.1 and PyTorch 1.8

**Comment by HuangZhe885** [comment]
> You might need to add the corresponding parameter for voxel feature and the correct input feature size in the yaml config file. Since I am recently traveling and not able to check the details of the errors but maybe you can try the fpvrcnn branch of this repo https://github.com/YuanYunshuang/OpenCOOD
> 
> This is the runnable old version. The recent updates of the official repo have many changes that might not support FPV-RCNN anymore and is not maintained anymore because this model is not very compatible with the other part of the code. And I recommend you to use spconv1.2.1 and PyTorch 1.8

**Thank you for responding，I am extremely grateful！**
 I'd want to pose the final question, which is contained in the paper: use IOU prediction to adjust positioning confidence. I didn't discover the code for the exact implementation of this formula, and I didn't see the code for D-NMS. Is the requested API encapsulated?

**Comment by YuanYunshuang** [comment]
It is at line 91-93 of opencood/data_utils/post_processor/fpvrcnn_postprocessor.py

**Comment by HuangZhe885** [comment]
> It is at line 91-93 of opencood/data_utils/post_processor/fpvrcnn_postprocessor.py

Thank you for assisting me; you are really helpful to someone like me who is just starting started; **thank you again!**
