### ISSUE TITLE
Timestamp vs frame notation

### ISSUE THREAD

**Issue by roshambo919** [DerrickXuNu/OpenCOOD#64]
Hi thanks for this great repo. One question for clarification - in the tutorials online, you use "timestamp" to describe what I would say is more like a "frame" (i.e. 000218 is a frame number). Can you confirm if the simulation is stepped with a fixed rate, and if so, are the data entries in the OPV2V dataset saved at 10 Hz or something else? Thanks!

**Comment by DerrickXuNu** [comment]
Yes, it is fixed frame rate with 10Hz
