### ISSUE TITLE
The function of the remove_large_pred_bbx  is wrong.

### ISSUE THREAD

**Issue by YileiWang-star** [DerrickXuNu/OpenCOOD#66]
The calculation of bbx_z_max, bbx_z_min in OpenCOOD/opencood/utils/box_utils.py/remove_large_pred_bbx(bbx_3d) function is wrong

**Comment by DerrickXuNu** [comment]
you are correct. I have fixed it.

**Comment by YileiWang-star** [comment]
What does the coordinate system in the opv2v dataset look like? A left-handed coordinate system?




easy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DerrickXuNu/OpenCOOD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DerrickXuNu/OpenCOOD] The function of the remove_large_pred_bbx  is wrong. (Issue #66)





 
Closed #66 as completed.
