### ISSUE TITLE
The coordinate system in the opv2v dataset

### ISSUE THREAD

**Issue by YileiWang-star** [DerrickXuNu/OpenCOOD#67]
What does the coordinate system in the opv2v dataset look like? A left-handed coordinate system?

**Comment by DerrickXuNu** [comment]
yes

**Comment by YileiWang-star** [comment]
---Original---
From: "Runsheng ***@***.***&gt;
Date: Sat, Apr 1, 2023 22:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DerrickXuNu/OpenCOOD] The coordinate system in the opv2v dataset(Issue #67)




 
yes
