### ISSUE TITLE
Some urls of Results on OPV2V dataset Table is invalid

### ISSUE THREAD

**Issue by susanbao** [DerrickXuNu/OpenCOOD#7]
Hello, I found some url links of Results on OPV2V dataset Table is invalid, such as early fusion of PointPillar. Could you please fix it?

**Comment by DerrickXuNu** [comment]
Hi, I think PointPillar early fusion's url is valid, could you double check it? We have provided most of the pretrained  weights for different fusion methods in the benchmark, and there are one or two invalid urls, representing the models that we haven't uploaded. Those urls will be fixed once we upload them.

**Comment by susanbao** [comment]
Hi, For PointPillar early fusion, in the link, it only contains pointpillar_attentive_fusion.zip. Maybe there are some mistakes. Thank you.

**Comment by DerrickXuNu** [comment]
Hi, it is fixed now, please have a look.

**Comment by susanbao** [comment]
I got it. Thanks.
