### ISSUE TITLE
Will the openCOOD support mmdetection3d in the future?

### ISSUE THREAD

**Issue by chensiweiTHU** [DerrickXuNu/OpenCOOD#70]
Thank you for developing the openCOOD. I have been using openCOOD for 3 months. Recently I am trying to expand my 3D detection  algorithm implented with mmdetection3D to collaborative perception. Most of the SOTA algorithms are powered by mmdetection, but the mmdetection framework is complicated. If this repository supports mmdetection 3D in the future, it will be much easier to import SOTA methods from stand-alone perception and let the researchers focus on cooperation itself. More over, this repository may receive more attention. So do you have plan to support mmdetection in the future? I am looking forward to your reply, thank you for reading.

**Comment by DerrickXuNu** [comment]
Thanks for using OpenCOOD.As you mentioned, mmdet is complicated to use, but I want to make the whole repo easy to use. Furthermore, as you point out, the key of the cooperative perception is tue collaboration part, so the backbone doesn't really play a critical role here. Therefore, I have no plan for mmdetection3d support
