### ISSUE TITLE
Question about the version of spconv and torch

### ISSUE THREAD

**Issue by lubin202209** [DerrickXuNu/OpenCOOD#71]
Dear author, my CUDA version is 10.2, so can I install the adapted spconv version directly through the command pip install spconv-cu102?

**Comment by DerrickXuNu** [comment]
Yes, I think so.

**Comment by lubin202209** [comment]
Thanks for your reply. I have another question, Do you have a plan to support DiscoNet、When2com and Who2com in the future?
