### ISSUE TITLE
Fail to reproduce inference.py

### ISSUE THREAD

**Issue by CSwakeQAQ** [DerrickXuNu/OpenCOOD#74]
Thank you very much for developing the openCOOD.When I reproduce opencood.I run “python opencood/tools/inference.py - model_dir ${CHECKPOINT_FOLDER} - fusion_method ${FUSION_STRATEGY} --show_sequence” 
,and I met with the following error: 
```
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
Traceback (most recent call last):
  File "opencood/tools/inference.py", line 203, in <module>
    main()
  File "opencood/tools/inference.py", line 86, in main
    vis.get_render_option().background_color = [0.05, 0.05, 0.05]
AttributeError: 'NoneType' object has no attribute 'background_color'
```
I guess whether this error is caused by my installation of the wrong version of open3d.I have tried to the lower version of open3d,but the error still hasn't been solved.Therefore, I would like to ask how to solve this error.If it is because of the version of open3d, could you please tell me the specific version number of open3d you adopted?

**Comment by IndigoChildren** [comment]
Maybe You should project the visulized image to remote servers

**Comment by DerrickXuNu** [comment]
It could be the graphic card issue as well. Can you run it without using --show_sequence flag?

**Comment by CSwakeQAQ** [comment]
> It could be the graphic card issue as well. Can you run it without using --show_sequence flag?

Thank you for your reply.I have checked the evaluation works well without using --show_sequence flag.Should I switch to another devices to test whether it can work on other graphic cards?

**Comment by DerrickXuNu** [comment]
Yes, please try that

**Comment by CSwakeQAQ** [comment]
> Maybe You should project the visulized image to remote servers

I do use remote servers to run this code.And i didn't understand the meaning of  "project the visulized image to remote servers".Could you give me some further explannation about projecting the visulized image to remote servers.

**Comment by CSwakeQAQ** [comment]
> Yes, please try that

I noted that setting this parameter will create a window to visualize,but i run this on remote servers.I wonder whether that is the reason why i fail to evaluate with  --show_sequence flag?

**Comment by CSwakeQAQ** [comment]
> yes, if you are run this on remote server it will show such error, this happens to me before.

Is there a way to run this on remote server or I can only run with --show_sequence flag on Local host？

**Comment by CSwakeQAQ** [comment]
> How did you solve it?
Just do not run this on remote server.Try on local host.
