### ISSUE TITLE
Question about the coordinate transformation in the post process

### ISSUE THREAD

**Issue by ellen19967** [DerrickXuNu/OpenCOOD#76]
Thanks for the great work. I have some questions about the coordinate transformation. The original point cloud has been projected to the coordinate of the ego vehicle before fusion. but why the bounding box will be projected again during post process stage?

` # convert output to bounding box
            if len(boxes3d) != 0:
                # (N, 8, 3)
                boxes3d_corner = \
                    box_utils.boxes_to_corners_3d(boxes3d,
                                                  order=self.params['order'])
                # (N, 8, 3)
                projected_boxes3d = \
                    box_utils.project_box3d(boxes3d_corner,
                                            transformation_matrix)`

**Comment by DerrickXuNu** [comment]
Hi, thanks for using opencood! 

This is mainly used for a unified coding format. For late fusion, the bounding box detection is not projected to ego, so the postprocess needs to do it.  But for intermediate and early fusion, the transformation_matrix will be an identity matrix, which won't have any effect on the bounding box. In this way, I can use the same code  for three different fusion strategty.

**Comment by ellen19967** [comment]
Okay now it makes sense, thanks for the immediate response.
