### ISSUE TITLE
Questions when testing?

### ISSUE THREAD

**Issue by lubin202209** [DerrickXuNu/OpenCOOD#77]
Hello, when I try to run the inference.py to test my trained v2vnet model, I got a result that the ap30\ap50\ap70 are all 0 like this, 
![9f4183b4458debc82e28501d46b5bce](https://user-images.githubusercontent.com/116709464/233890485-a2eec771-1b2f-4347-8d6b-96756fe79fb3.png)
The command I typed in the terminal is "CUDA_VISIBLE_DEVICES=0 --model_dir opencood/logs/2023_04_13_07_04_01 --fusion_method intermediate"
I have already set the validate_dir in the config.yaml as opv2v/test like this
![587e511bebc5ef0254d1578527d55b1](https://user-images.githubusercontent.com/116709464/233890849-18fc44bd-a6a6-4b49-bc35-ebdb59a07e62.png)
could you please help me to find out where is the problem and how to fix it?

**Comment by DerrickXuNu** [comment]
Are you able to get normal AP for the other models? V2VNet usually takes longer time to train, and sometimes it doesn't converge well.

**Comment by lubin202209** [comment]
I have just test the trained where2comm model, it get the normal results like this,
![9cc3961a6fca7801df0ad03433bd288](https://user-images.githubusercontent.com/116709464/233893448-2505ca47-948c-4286-9791-9cfb2a21fb48.png)

**Comment by lubin202209** [comment]
> Are you able to get normal AP for the other models? V2VNet usually takes longer time to train, and sometimes it doesn't converge well.
So as the v2vnet sometimes can't converge well, how can I fix the problem?

**Comment by lubin202209** [comment]
The config when I train the v2vnet model is like this,
![8603604ce7a5bd8a8bfd1f849c20d17](https://user-images.githubusercontent.com/116709464/233894084-815be22a-fb4d-4fc4-954b-334561c76337.png)
![03938718e6862f4b4ee2b9e5a3e3ef7](https://user-images.githubusercontent.com/116709464/233894108-76284424-3412-4240-a6b6-45cd921fb4ea.png)

**Comment by DerrickXuNu** [comment]
This config looks good to me. There are two ways to solve this:
1) Train a late fusion model first to train the backbone, and then load the pretrained backbone and train your v2vnet
2) Train from my provided v2vnet checkpoint

**Comment by lubin202209** [comment]
Thanks for your advice, I will have a try. What's more, I have another question, I found that the defined function "inference_intermediate_fusion" in opencood/tools/inference_utils.py returns "return inference_early_fusion(batch_data, model, dataset)" like this,
![baddfd5273cb407e543cb7ed9d9516e](https://user-images.githubusercontent.com/116709464/233895892-5bf5e369-5263-4d74-8918-6e17191a96c9.png)
Does that mean the two methods "earlyfusion" and "intermediatefusion" are the same?

**Comment by DerrickXuNu** [comment]
Did you fix the issue? I will close the issue if everything works
