### ISSUE TITLE
Questions about the shrink_header?

### ISSUE THREAD

**Issue by lubin202209** [DerrickXuNu/OpenCOOD#79]
Hello, I have a question about the shrink_header. Could you please tell me what's the meaning of shrink_header here as I can use the compression to compress the features?
![d94a739c881517ff69c789129c457ba](https://user-images.githubusercontent.com/116709464/236221334-cd2a51d7-54fb-4ff9-aa80-23bf7b9d7815.png)
![273060e3c248facf250ba006820773d](https://user-images.githubusercontent.com/116709464/236221384-b6c5994f-cfaf-4252-b003-677aa2511567.png)
![0ca5c52738ce0a8cbd0ed9c1bd67f51](https://user-images.githubusercontent.com/116709464/236221533-3a94a790-da13-4f95-9f10-cc407c82d082.png)

**Comment by DerrickXuNu** [comment]
It is mainly used to shrink the spatial resolution to save GPU computation cost and training time.

**Comment by lubin202209** [comment]
Because I don't want to use shrink_head or compress, I set the flags of both to false. At this time, I want to train the pointpillar_v2xvit model. I set the feature_stride in the yaml file postprocess to 2 like below.
![bf40801007bebd04e4b24a29d05a20b](https://user-images.githubusercontent.com/116709464/236376081-5b79ca08-8af9-4d7f-b36a-c4e50604504f.png)
How can I set the parameters in the yaml file transformer so that the size of the tensor shape can match?
![d75fd8ec2fd4d5b6ec72c2fc369fc76](https://user-images.githubusercontent.com/116709464/236376201-938931c1-65c5-4a4a-9446-df62032aa232.png)

**Comment by DerrickXuNu** [comment]
You can still use shrink header but change the stride from 2 to 1, so it will only modify the channel for the ViT to directly use and won't have big impact on the performance . If you insist to remove the whole head, then you need to adjust the channel number in ViT

**Comment by lubin202209** [comment]
Yes, I insist to remove the whole head, I change the config "dim" in the cav_att_config and the config "dim" in the pwindow_att_config and the config "mlp_dim" in the feed_forward from the original 256 to 384 like below, however, related errors about tensor size mismatch will still be reported during the training process, so could you please explain in more detail how to adjust the channel number?
![4ea6749bf3d16934f6307bbe1f13860](https://user-images.githubusercontent.com/116709464/236412724-4c9e1cd9-5927-48c8-8803-5fe668eb0ab3.png)

**Comment by lubin202209** [comment]
Yes, I insist to remove the whole head, I change the config "dim" in the cav_att_config and the config "dim" in the pwindow_att_config and the config "mlp_dim" in the feed_forward from the original 256 to 384 like below, however, related errors about tensor size mismatch will still be reported during the training process, so could you please explain in more detail how to adjust the channel number?
![4ea6749bf3d16934f6307bbe1f13860](https://user-images.githubusercontent.com/116709464/236413013-ccd9bbc0-f548-49d6-8c0a-9d56a454aafd.png)
![2d2ab3cc93ed35567b7b02870fcfe83](https://user-images.githubusercontent.com/116709464/236413423-c8a44b83-3d51-4df2-bb63-d3c89d0a59b2.png)
