### ISSUE TITLE
How to get the no fusion results?

### ISSUE THREAD

**Issue by susanbao** [DerrickXuNu/OpenCOOD#8]
Hello, in your paper, there are experiment results on no fusion part. But there is no corresponding yaml files on no fusion. How do you get the results? Train and test with OpenPCDet on opv2v data?

**Comment by DerrickXuNu** [comment]
Hi, this is easy to achieve with minimum extra coding. Use late fusion strategy but don't include any other cav's results in the late fusion stage.

**Comment by CARLAlover** [comment]
Just an alternative approach: I implemented no fusion by removing all the LiDAR pcd from other CAV but keep the groundtruth there.

**Comment by susanbao** [comment]
> Hi, this is easy to achieve with minimum extra coding. Use late fusion strategy but don't include any other cav's results in the late fusion stage.

Would it be correct if I get the test results of no fusion by using the training strategy of late fusion and without including any other cav's results in the inference_late_fusion function?

**Comment by DerrickXuNu** [comment]
yes, that is correct, although myself separately train the models for no fusion (I didn't use the already-trained late fusion model directly). But you can do the thing you said also if you want to save some time.

**Comment by susanbao** [comment]
> yes, that is correct, although myself separately train the models for no fusion (I didn't use the already-trained late fusion model directly). But you can do the thing you said also if you want to save some time.

Thank for your help.

**Comment by shaojiabing** [comment]
> Hi, this is easy to achieve with minimum extra coding. Use late fusion strategy but don't include any other cav's results in the late fusion stage.

Hello,Please tell me what should I do to achieve this?
