### ISSUE TITLE
Point cloud range

### ISSUE THREAD

**Issue by YileiWang-star** [DerrickXuNu/OpenCOOD#82]
What is the 0 point of the point cloud range x,y,z?z=[-3,1] Does -1 correspond to the position of the lidar on top of the vehicle?
What is the height of the pillar above the ground?

**Comment by DerrickXuNu** [comment]
No, 0 is actually the lidar position. All detection is based on lidar coordinates

**Comment by YileiWang-star** [comment]
What is the z-coordinate of that ground? 
What is the height of the pillar above the ground?
Does z=-3 mean it is below the ground?

**Comment by DerrickXuNu** [comment]
No, the lidar is actually installed at a high position (vehicle height + 1m), so ground should be at -3m

**Comment by easy2star** [comment]
Your work plays a big role in collaborative perception and I have some questions for you:
1, is the following understanding correct?
As you said, the LIDAR is at position 0, which is 1 meter above the top of the vehicle, meaning that the height of the vehicle used for collaboration is 2 meters?

2, Is the height of the other vehicles in the scene (that will be detected) variable?  

3, Are the 3D coordinates of the LIDAR (0,0,0)?

4, Is the coordinate system of the LIDAR also left-handed when collecting other points in the scene, with the Z-axis vertically up the vehicle, the X-axis directly in front of the vehicle, and the Y-axis vertical to the right side of the vehicle and parallel to the ground?

5. Are the vehicles in all the scenes in the dataset on the same level, i.e., are the coordinates of the ground in the scenes in different folders all Z=-3, and does the height of the ground change with the position of the vehicle? For example, real world roads may be high and low, have pothole roads, etc?

Thank you. I look forward to hearing from you.
