### ISSUE TITLE
KeyError: 'D:\\OpenCOOD\\validate\\2021_08_21_17_30_41\\4279\\000069.yaml when executing visualizing and training command in terminal on Windows

### ISSUE THREAD

**Issue by michaeltan53** [DerrickXuNu/OpenCOOD#88]
Hi, I'm trying to run the command _python opencood/visualization/vis_data_sequence.py --color_mode ${COLOR_RENDERING_MODE}"constant"_ on Windows, while it returns a KeyError **KeyError: 'D:\\OpenCOOD\\validate\\2021_08_21_17_30_41\\4279\\000069.yaml'**  for the line of code 
**load_yaml(cav_content[timestamp_key]['yaml'])['lidar_pose']**  
in the file **basedataset.py**. Why does it happen and how can I solve it? Many thanks.

**Comment by DerrickXuNu** [comment]
Did you solve the issue already? I think it is mainly caused by windows's os path.

**Comment by michaeltan53** [comment]
> Did you solve the issue already? I think it is mainly caused by windows's os path.

Not yet, I cannot solve this problem on Windows, but I'm able to run the project on both MacOS and Linux system environment
