### ISSUE TITLE
'Spawn collision' error during replay

### ISSUE THREAD

**Issue by xavhl** [DerrickXuNu/OpenCOOD#91]
ERROR: Spawn failed because of collision at spawn position 

Is this supposed to happen when we are replaying the original OPV2V dataset? I assumed that there should be no collision, as the vehicles should have been appropriately placed when creating the dataset.

**Comment by DerrickXuNu** [comment]
Is the error still happening? What is your CARLA version?

**Comment by xavhl** [comment]
I figured out that it was due to the iterative trial of vehicle spawning [line 257 scene_manager.py](https://github.com/DerrickXuNu/OpenCOOD/blob/64007d453740939df8911ce7d67b75372b50053d/logreplay/scenario/scene_manager.py#L257) in the end all vehicles were successfully created given appropriate z-coordinate 

```python
while not vehicle:
    cur_pose.location.z += 0.01
    vehicle = world.try_spawn_actor(cav_bp, cur_pose)
```

![image](https://github.com/DerrickXuNu/OpenCOOD/assets/50361174/128bc9a2-6baf-4159-ab6e-8c29e547d01b)
