### ISSUE TITLE
Question about customized datasets based on unity 

### ISSUE THREAD

**Issue by CSwakeQAQ** [DerrickXuNu/OpenCOOD#96]
I made a customized datasets of ships at sea using unity(loaded each ship with radar sensors to collect the point cloud data).After collecting these data,I converted the resulting data into V2X dataset format,and I was sure that the labels I generated using unity were correct.During the conversion process,I tried my best to align the data form (such as radar position, camera position, Angle, etc.) with the v2x format,but when I was running inference.py --show_seqence for visualization results,I found that the gt box of my self-made dataset was far from the position of the ship itself.I only modified the v2x collaborative vehicle awareness range and voxel size to match the size of the ship at sea,I am currently reading some details of OpenCOOD code to try to solve this problem,but there are many framework module parameters, I was wondering if you have any suggestions (e.g. what parameters should I focus on modifying to solve this problem?) Thank you so much!
<img width="432" alt="image" src="https://github.com/DerrickXuNu/OpenCOOD/assets/115983829/09beddb4-5a71-43be-81ca-13d980633cfc">

**Comment by DerrickXuNu** [comment]
This looks like a very interesting project! I saw you close the issue, so you have solved it ？

**Comment by CSwakeQAQ** [comment]
Almost, I modified part of the data flow in the basedataset.py to match my data. Now the center of the target frame can be aligned with the ship,but there are still some problems with the rotation Angle,which I am trying to solve. Because I have solved the main problem,I closed the issue: )

**Comment by CSwakeQAQ** [comment]
Almost, I modified part of the data flow in the basedataset.py to match my data. Now the center of the gt box can be aligned with the ship,but there are still some problems with the rotation Angle,which I am trying to solve. Because I have solved the main problem,I closed the issue: )
