### ISSUE TITLE
How to adjust the communication Volume

### ISSUE THREAD

**Issue by HuangZhe885** [DerrickXuNu/OpenCOOD#98]
Thank you for your excellent work.  I use the formula   log2 ( |M(k)| × D × 32/8) to calculate communication Volume, the calculation result is about 23~25. What should I do if I wish to manually lower this value? minimize the compression ratio or the feature size? I tried changing the compression ratio, but the Volume didn't go down.

<img width="654" alt="image" src="https://github.com/DerrickXuNu/OpenCOOD/assets/44192081/4a556258-64eb-458e-aac4-e7bf5d37f06f">

**Comment by DerrickXuNu** [comment]
Sorry for the late response. Can you paste your code of calculating volume here?

**Comment by HuangZhe885** [comment]
> Sorry for the late response. Can you paste your code of calculating volume here?
 Thank you for your reply,  I wrote this using the formula in the where2comm paper, but I'm not sure if it's correct.

`non_zero_elements = communication_masks.nonzero().size(0)
  communication_volume = math.log2(non_zero_elements * C * 32 / 8)
   print("communication_volume",communication_volume)`

**Comment by DerrickXuNu** [comment]
Changing compression rate should work as it will reduce the C. Please check if you are giving the right C (i.e., the feature dimension after compression ) to your Romulo

**Comment by besma14** [comment]
I am unable to reduce the communication volume even when adjusting the compression rate in where2comm. Could you help me?
